# Development Environment
version: "3"

services:

# Jupyter Development Server
  notebook:
    build: setup/notebook
    volumes:
      - ./src:/home/jovyan/work
      - ./mlruns:/home/jovyan/mlruns 
    ports:
      - 8888:8888
    container_name: notebook-container

# ML Model Tracking Server 
  mlflow:
      container_name: mlflow
      build: setup/mlflow
      ports: 
      - "5000:5000" # map mlflow's default 5000 to desired port
      environment:
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 
      command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mlflow_db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow/ --host 0.0.0.0

# ML Model Database
  minio:
      restart: always
      image: minio/minio:RELEASE.2021-10-13T00-23-17Z
      container_name: mlflow_s3
      env_file:
          - .env
      ports:
          - "9000:9000"
          - "9001:9001"
      command: server /data --console-address ':9001' --address ':9000'
      environment:
          - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
          - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      volumes:
          - minio_data:/data

# Create "Model" Bucket
  minio_client:
      image: minio/mc:RELEASE.2021-10-07T04-19-58Z
      depends_on:
          - minio
      container_name: minio_client
      env_file:
          - .env
      entrypoint: >
          /bin/sh -c "
          /tmp/wait.sh minio:9000;
          /usr/bin/mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
          /usr/bin/mc mb minio/models;
          exit 0;
          "
      volumes:
          - ./wait.sh:/tmp/wait.sh

# Model Database
  mlflow_db:
        restart: always
        image: mysql/mysql-server:5.7.28
        container_name: mlflow_db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
            
  
volumes:
  dbdata:
  minio_data: